const SET_PROFILE = 'SET_PROFILE';
const UPDATE_PROFILE = 'UPDATE_PROFILE';
const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
const SET_LOGOUT = 'SET_LOGOUT';

//Photo Editor
const SET_EDITOR_VALUES = 'SET_EDITOR_VALUES';
const ADD_ITEM = 'ADD_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM';
const SET_FRAME = 'SET_FRAME';
const ADD_FRAME = 'ADD_FRAME';
const SET_BACKGROUND_SIZE = 'SET_BACKGROUND_SIZE';

const ADD_PHOTO = 'ADD_PHOTO';
const ADD_CANVAS = 'ADD_CANVAS';
const ADD_TEXT = 'ADD_TEXT';
const UPDATE_TEXT_STYLE = 'UPDATE_TEXT_STYLE';
const UPDATE_IMAGE_STYLE = 'UPDATE_IMAGE_STYLE';
const ADD_BACKGROUND_REMOVED_IMAGE = 'ADD_BACKGROUND_REMOVED_IMAGE';
const UPDATE_CANVAS_STYLE = 'UPDATE_CANVAS_STYLE';
const REMOVE_FRAME = 'REMOVE_FRAME';
const REMOVE_PHOTO = 'REMOVE_PHOTO';
const REMOVE_TEXT = 'REMOVE_TEXT';
const SELECTED_ITEM = 'SELECTED_ITEM';
const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';
const REMOVE_ACTIVE_ITEM = 'REMOVE_ACTIVE_ITEM';
const CHANGE_TEXT_POSITION = 'CHANGE_TEXT_POSITION';
const CHANGE_IMAGE_POSITION = 'CHANGE_IMAGE_POSITION';
const CHANGE_CANVAS_POSITION = 'CHANGE_CANVAS_POSITION';
const SET_UPDATE_TEXT = 'SET_UPDATE_TEXT';
const SET_UPDATE_PHOTO = 'SET_UPDATE_PHOTO';
const SET_UPDATE_CANVAS = 'SET_UPDATE_CANVAS';
const SET_UPDATED_TEXT = 'SET_UPDATED_TEXT';
const SET_UPDATED_PHOTO = 'SET_UPDATED_PHOTO';
const SET_UPDATED_CANVAS = 'SET_UPDATED_CANVAS';
const PASS_CANVAS_ACTIONS = 'PASS_CANVAS_ACTIONS';
const SET_BACK_IMAGES = 'SET_BACK_IMAGES';
const REMOVE_BACK_IMAGES = 'REMOVE_BACK_IMAGES';
const TOGGLE_AI_IMAGE = 'TOGGLE_AI_IMAGE';

export {
	SET_PROFILE,
	SET_LOGGED_IN_USER,
	SET_LOGOUT,
	UPDATE_PROFILE,
	SET_EDITOR_VALUES,
	ADD_ITEM,
	REMOVE_ITEM,
	SET_FRAME,
	ADD_FRAME,
	ADD_PHOTO,
	ADD_TEXT,
	REMOVE_FRAME,
	REMOVE_PHOTO,
	REMOVE_TEXT,
	SELECTED_ITEM,
	SET_BACKGROUND_SIZE,
	UPDATE_IMAGE_STYLE,
	UPDATE_TEXT_STYLE,
	SET_ACTIVE_ITEM,
	REMOVE_ACTIVE_ITEM,
	CHANGE_TEXT_POSITION,
	CHANGE_IMAGE_POSITION,
	SET_UPDATE_TEXT,
	SET_UPDATED_TEXT,
	SET_UPDATED_PHOTO,
	SET_UPDATE_PHOTO,
	ADD_CANVAS,
	SET_UPDATED_CANVAS,
	SET_UPDATE_CANVAS,
	UPDATE_CANVAS_STYLE,
	CHANGE_CANVAS_POSITION,
	PASS_CANVAS_ACTIONS,
	SET_BACK_IMAGES,
	REMOVE_BACK_IMAGES,
	ADD_BACKGROUND_REMOVED_IMAGE,
	TOGGLE_AI_IMAGE
};
